language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
before_script:
  npm install
script:
  npm test
  npm run build
notifications:
  email: false
deploy:
  provider: pages
  local-dir: dist
  target-branch: master
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  fqdn: proto.school
  on:
    branch: code
